spring:
  datasource:
    url: ${DB_MYSQL_URL}?serverTimezone=Asia/Seoul # db 시간대 설정
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul # Hibernate 타임존 설정

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_ID}
            client-secret: ${OAUTH_GOOGLE_SECRET}
            redirect-uri: ${OAUTH_GOOGLE_REDIRECT}
            scope:
              - email
              - profile

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_VALIDITY}

logging.level:
  org.hibernate:
    SQL: DEBUG
    type: trace

# swagger 관련 설정
springdoc:
  # API 문서 관련 설정
  api-docs:
    enabled: true          # 기본값: true
    path: /api-docs        # API 문서 JSON 경로 (기본값: /v3/api-docs)
  # Swagger UI 관련 설정
  swagger-ui:
    path: /swagger-ui.html             # Swagger UI 페이지 경로
    disable-swagger-default-url: true   # 기본 petstore 예제 URL 비활성화
    groups-order: DESC                  # Tag의 알파벳 내림차순으로 정렬
    operationsSorter: method            # API 목록을 HTTP 메서드 순으로 정렬(GET, POST, PUT, DELETE 순)
  # API 기본 설정
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  # API 경로 패턴 설정
  paths-to-match:
    - /**             # /로 시작하는 경로만 문서화

# swagger 서버 분리
swagger:
  server:
    http-url: ${SERVER_HTTP_URL}
    https-url: ${SERVER_HTTPS_URL}

# 알라딘 Open API 상품 검색 관련 설정
aladin:
  api:
    url: https://www.aladin.co.kr/ttb/api/ItemSearch.aspx?QueryType=Keyword&SearchTarget=All&Cover=Big&Output=JS
    # 검색어 종류: 제목+저자, 검색 대상: 전체, 표지 이미지 크기: 가장 큰 크기, 출력방법: JSON
    ttbkey: ${ALADIN_TTB_KEY}